/**
 * Module 1 — Chess Pieces curriculum (Lichess Learn parity).
 * 34 exercises across 6 chapters.
 */

export const MODULE1_SECTION = {
  title: "Chess pieces",
  slug: "chess-pieces",
  description: "Learn how each piece moves — move the piece to collect every star.",
  icon: "FaGraduationCap",
  order: 0,
  difficulty: "beginner",
  estimatedMinutes: 45,
};

export const MODULE1_CHAPTERS = [
  {
    title: "The Rook",
    slug: "the-rook",
    icon: "FaChessRook",
    description: "It moves in straight lines.",
    lichessStageId: 1,
    exercises: [
      {
        title: "Move the rook",
        description: "Grab all the stars!",
        fen: "8/8/8/8/8/8/4R3/8 w - - 0 1",
        playerPieces: [{ square: "e2", type: "r", color: "w" }],
        targetSquares: ["e7"],
        optimalMoveCount: 1,
        hintArrows: [{ from: "e2", to: "e7" }],
      },
      {
        title: "Grab all the stars",
        description: "Grab all the stars!",
        fen: "8/2R5/8/8/8/8/8/8 w - - 0 1",
        targetSquares: ["c5", "g5"],
        optimalMoveCount: 2,
        hintArrows: [{ from: "c7", to: "c5" }, { from: "c5", to: "g5" }],
      },
      {
        title: "Fewest moves",
        description: "Grab all the stars in as few moves as possible.",
        fen: "8/8/8/8/3R4/8/8/8 w - - 0 1",
        targetSquares: ["a4", "g3", "g4"],
        optimalMoveCount: 3,
      },
      {
        title: "Fewest moves",
        description: "Grab all the stars in as few moves as possible.",
        fen: "7R/8/8/8/8/8/8/8 w - - 0 1",
        targetSquares: ["f8", "g1", "g7", "g8", "h7"],
        optimalMoveCount: 5,
      },
      {
        title: "Use both rooks",
        description: "Use both rooks to grab all the stars.",
        fen: "8/1R6/8/8/3R4/8/8/8 w - - 0 1",
        targetSquares: ["a4", "g3", "g7", "h4"],
        optimalMoveCount: 4,
      },
      {
        title: "Use both rooks",
        description: "Use both rooks to grab all the stars.",
        fen: "8/8/8/8/8/5R2/8/R7 w - - 0 1",
        targetSquares: ["b7", "d1", "d5", "f2", "f7", "g4", "g7"],
        optimalMoveCount: 7,
      },
    ],
  },
  {
    title: "The Bishop",
    slug: "the-bishop",
    icon: "FaChessBishop",
    description: "It moves diagonally.",
    lichessStageId: 2,
    exercises: [
      {
        title: "Grab all the stars",
        description: "Grab all the stars!",
        fen: "8/8/8/8/8/5B2/8/8 w - - 0 1",
        targetSquares: ["d5", "g8"],
        optimalMoveCount: 2,
        hintArrows: [{ from: "f3", to: "d5" }, { from: "d5", to: "g8" }],
      },
      {
        title: "Fewest moves",
        description: "Grab all the stars in as few moves as possible.",
        fen: "8/8/8/8/8/1B6/8/8 w - - 0 1",
        targetSquares: ["a2", "b1", "b5", "d1", "d3", "e2"],
        optimalMoveCount: 6,
      },
      {
        title: "Grab all the stars",
        description: "Grab all the stars!",
        fen: "8/8/8/8/3B4/8/8/8 w - - 0 1",
        targetSquares: ["a1", "b6", "c1", "e3", "g7", "h6"],
        optimalMoveCount: 6,
      },
      {
        title: "Grab all the stars",
        description: "Grab all the stars!",
        fen: "8/8/8/8/2B5/8/8/8 w - - 0 1",
        targetSquares: ["a4", "b1", "b3", "c2", "d3", "e2"],
        optimalMoveCount: 6,
      },
      {
        title: "Use both bishops",
        description: "You need both bishops to grab all the stars.",
        fen: "8/8/8/8/8/8/8/2B2B2 w - - 0 1",
        targetSquares: ["d3", "d4", "d5", "e3", "e4", "e5"],
        optimalMoveCount: 6,
      },
      {
        title: "Use both bishops",
        description: "You need both bishops to grab all the stars.",
        fen: "8/3B4/8/8/8/2B5/8/8 w - - 0 1",
        targetSquares: ["a3", "c2", "e7", "f5", "f6", "g8", "h4", "h7"],
        optimalMoveCount: 11,
      },
    ],
  },
  {
    title: "The Queen",
    slug: "the-queen",
    icon: "FaChessQueen",
    description: "Queen = rook + bishop.",
    lichessStageId: 3,
    exercises: [
      {
        title: "Grab all the stars",
        description: "Grab all the stars!",
        fen: "8/8/8/8/8/8/4Q3/8 w - - 0 1",
        targetSquares: ["e5", "b8"],
        optimalMoveCount: 2,
        hintArrows: [{ from: "e2", to: "e5" }, { from: "e5", to: "b8" }],
      },
      {
        title: "Grab all the stars",
        description: "Grab all the stars!",
        fen: "8/8/8/8/3Q4/8/8/8 w - - 0 1",
        targetSquares: ["a3", "f2", "f8", "h3"],
        optimalMoveCount: 4,
      },
      {
        title: "Grab all the stars",
        description: "Grab all the stars!",
        fen: "8/8/8/8/2Q5/8/8/8 w - - 0 1",
        targetSquares: ["a3", "d6", "f1", "f8", "g3", "h6"],
        optimalMoveCount: 6,
      },
      {
        title: "Grab all the stars",
        description: "Grab all the stars!",
        fen: "8/6Q1/8/8/8/8/8/8 w - - 0 1",
        targetSquares: ["a2", "b5", "d3", "g1", "g8", "h2", "h5"],
        optimalMoveCount: 7,
      },
      {
        title: "Grab all the stars",
        description: "Grab all the stars!",
        fen: "8/8/8/8/8/8/8/4Q3 w - - 0 1",
        targetSquares: ["a6", "d1", "f2", "f6", "g6", "g8", "h1", "h4"],
        optimalMoveCount: 9,
      },
    ],
  },
  {
    title: "The King",
    slug: "the-king",
    icon: "FaChessKing",
    description: "The most important piece.",
    lichessStageId: 4,
    exercises: [
      {
        title: "The king is slow",
        description: "The king moves one square at a time. Reach the star.",
        fen: "8/8/8/8/8/3K4/8/8 w - - 0 1",
        targetSquares: ["e6"],
        optimalMoveCount: 3,
        hintArrows: [
          { from: "d3", to: "d4" },
          { from: "d4", to: "d5" },
          { from: "d5", to: "e6" },
        ],
      },
      {
        title: "Grab all the stars",
        description: "Grab all the stars!",
        fen: "8/8/8/8/8/8/8/4K3 w - - 0 1",
        targetSquares: ["c2", "d3", "e2", "e3"],
        optimalMoveCount: 4,
      },
      {
        title: "Last one",
        description: "Grab all the stars!",
        fen: "8/8/8/4K3/8/8/8/8 w - - 0 1",
        targetSquares: ["b5", "c5", "d6", "e3", "f3", "g4"],
        optimalMoveCount: 8,
      },
    ],
  },
  {
    title: "The Knight",
    slug: "the-knight",
    icon: "FaChessKnight",
    description: "It moves in an L shape.",
    lichessStageId: 5,
    exercises: [
      {
        title: "Knights move in an L",
        description: "Knights have a fancy way of jumping! Grab all the stars.",
        fen: "8/8/8/8/4N3/8/8/8 w - - 0 1",
        targetSquares: ["c5", "d7"],
        optimalMoveCount: 2,
        hintArrows: [{ from: "e4", to: "c5" }, { from: "c5", to: "d7" }],
      },
      {
        title: "Grab all the stars",
        description: "Grab all the stars!",
        fen: "8/8/8/8/8/8/8/1N6 w - - 0 1",
        targetSquares: ["c3", "d4", "e2", "f3", "f7", "g5", "h8"],
        optimalMoveCount: 8,
      },
      {
        title: "Grab all the stars",
        description: "Grab all the stars!",
        fen: "8/2N5/8/8/8/8/8/8 w - - 0 1",
        targetSquares: ["b6", "d5", "d7", "e6", "f4"],
        optimalMoveCount: 5,
      },
      {
        title: "Jump over obstacles",
        description: "Knights can jump over obstacles. Grab all the stars!",
        fen: "8/8/8/8/5N2/8/8/8 w - - 0 1",
        targetSquares: ["e3", "e4", "e5", "f3", "f5", "g3", "g4", "g5"],
        optimalMoveCount: 9,
      },
      {
        title: "Grab all the stars",
        description: "Grab all the stars!",
        fen: "8/8/8/8/8/3N4/8/8 w - - 0 1",
        targetSquares: ["c3", "e2", "e4", "f2", "f4", "g6"],
        optimalMoveCount: 6,
      },
      {
        title: "Grab all the stars",
        description: "Grab all the stars!",
        fen: "8/2N5/8/8/8/8/8/8 w - - 0 1",
        targetSquares: ["b4", "b5", "c6", "c8", "d4", "d5", "e3", "e7", "f5"],
        optimalMoveCount: 9,
      },
    ],
  },
  {
    title: "The Pawn",
    slug: "the-pawn",
    icon: "FaChessPawn",
    description: "It moves forward only.",
    lichessStageId: 6,
    exercises: [
      {
        title: "Pawns move forward",
        description: "Pawns move forward only. Reach the star (promotion may help).",
        fen: "8/8/8/P7/8/8/8/8 w - - 0 1",
        targetSquares: ["f3"],
        optimalMoveCount: 4,
        requiresPromotion: true,
        hintArrows: [
          { from: "a5", to: "a6" },
          { from: "a6", to: "a7" },
          { from: "a7", to: "a8" },
        ],
      },
      {
        title: "Promote to queen",
        description: "Promoting to a queen is usually best. Grab all the stars!",
        fen: "8/8/8/5P2/8/8/8/8 w - - 0 1",
        targetSquares: ["b6", "c4", "d7", "e5", "a8"],
        optimalMoveCount: 8,
        requiresPromotion: true,
      },
      {
        title: "Pawns move forward",
        description: "Pawns move forward. Grab all the stars!",
        fen: "8/8/8/8/8/4P3/8/8 w - - 0 1",
        targetSquares: ["c6", "d5", "d7"],
        optimalMoveCount: 4,
        hintArrows: [
          { from: "e3", to: "e4" },
          { from: "e4", to: "d5" },
          { from: "d5", to: "c6" },
        ],
        validationRules: {
          type: "playerPiecesOnlyOn",
          squares: ["e3", "e4", "c6", "d5", "d7"],
        },
      },
      {
        title: "Capture then promote",
        description: "Capture then promote. Grab all the stars!",
        fen: "8/8/8/8/8/1P6/8/8 w - - 0 1",
        targetSquares: ["b4", "b6", "c4", "c6", "c7", "d6"],
        optimalMoveCount: 8,
        requiresPromotion: true,
      },
      {
        title: "Capture then promote",
        description: "Capture then promote. Grab all the stars!",
        fen: "8/8/8/8/8/3P4/8/8 w - - 0 1",
        targetSquares: ["c4", "b5", "b6", "d5", "d7", "e6", "c8"],
        optimalMoveCount: 8,
        requiresPromotion: true,
        validationRules: {
          type: "forbiddenPawnSquares",
          squares: ["b5", "d4", "d6", "c7"],
        },
      },
      {
        title: "Use all the pawns",
        description: "Use all the pawns to grab every star.",
        fen: "8/8/8/8/8/P1PP3P/8/8 w - - 0 1",
        targetSquares: ["b5", "c5", "d4", "e5", "g4"],
        optimalMoveCount: 7,
      },
      {
        title: "Second rank pawn",
        description: "A pawn on the second rank can move two squares at once.",
        fen: "8/8/8/8/8/8/4P3/8 w - - 0 1",
        targetSquares: ["d6"],
        optimalMoveCount: 3,
        hintArrows: [{ from: "e2", to: "e4" }],
        validationRules: { type: "forbiddenPawnSquares", squares: ["e3"] },
      },
      {
        title: "No promotion needed",
        description: "Grab all the stars — no need to promote!",
        fen: "8/8/8/8/8/8/2PPPP2/8 w - - 0 1",
        targetSquares: ["c5", "d5", "e5", "f5", "d3", "e4"],
        optimalMoveCount: 9,
      },
    ],
  },
];
